architecture: replication

auth:
  enabled: true
  existingSecret: redis-secret

replica:
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: "fast"
    size: 50Gi

master:
  persistence:
    enabled: true
    storageClass: "fast"
    size: 50Gi

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
