serviceAccount:
  create: true
  name: fluent-bit

input:
  tail:
    enabled: true
    path: /var/log/containers/*.log
    parser: python_app_log
    tag: kube.*
    db: /fluent-bit/tail/pos.db
    refreshInterval: 5

parsers:
  customParsers: |
    [PARSER]
        Name        python_app_log
        Format      regex
        Regex       ^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+\-]\d{4}) (?<level>[A-Z]+) (?<module>[a-zA-Z0-9_.]+) (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S%z

filters:
  kubernetes:
    enabled: true
    match: kube.*
    mergeLog: true
    keepLog: true
    k8sLoggingParser: true
    k8sLoggingExclude: false

output:
  loki:
    enabled: true
    host: http://loki.observability.svc.cluster.local
    port: 3100
    labels:
      - "namespace"
      - "container_name"
      - "level"
      - "module"
    autoKubernetesLabels: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
