controller:
  replicaCount: 3
  ingressClass:
    create: true
    setAsDefaultIngress: true
  service:
    type: LoadBalancer
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 2Gi
  nodeSelector:
    kubernetes.io/os: linux
    ingress-node: "yes"
  tolerations:
    - key: "ingress-pod"
      operator: "Equal"
      value: "yes"
      effect: "NoExecute"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - ingress-nginx
          topologyKey: "kubernetes.io/hostname"
  config:
    proxy-connect-timeout: "10"
    proxy-read-timeout: "60"
    proxy-send-timeout: "60"
    use-proxy-protocol: "false"
    force-ssl-redirect: "true"
    server-tokens: "false"
  metrics:
    enabled: true
  securityContext:
    runAsUser: 101
    runAsGroup: 101
    fsGroup: 101
    readOnlyRootFilesystem: true
defaultBackend:
  enabled: true
