name: Check Schema Sync

on:
  pull_request:
    paths:
      - 'models/**'
      - 'schemas/validation/**'
      - 'scripts/export_schemas.py'

jobs:
  export-and-check-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Export schemas
        run: python scripts/export_schemas.py
      - name: Check for schema drift
        run: |
          git diff --exit-code schemas/validation/
