existingSecret: oauth2-proxy-secret
existingSecretMappings:
  clientIDKey: clientID
  clientSecretKey: clientSecret
  cookieSecretKey: cookieSecret
config:
  extraArgs:
    provider: "keycloak-oidc"
    redirect-url: "https://dashboard.example.com/oauth2/callback"
    oidc-issuer-url: "https://keycloak.example.com/realms/TWÓJ_REALM"
    pass-access-token: true
    set-authorization-header: true
    pass-user-headers: true
upstreams:
  - "http://kubernetes-dashboard.kubernetes-dashboard.svc.cluster.local:80"
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - dashboard.moaiops.com
  tls:
    - secretName: dashboard-tls
      hosts:
        - dashboard.moaiops.com
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
